services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shift_editor
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=xPH0A5L8wOqRcjNCcww9VGd2KRjMj9r4JrQ1XxpbJzs=
      - NEXT_PUBLIC_URL=http://localhost:3001
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shift_editor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 