name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: List repository contents
        run: ls -la
      
      - name: Test SSH connection
        run: |
          ssh -T git@github.com || true 